apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bunny-metrics.name" . }}-config
  labels:
    app: {{ .Values.name }}
data:
  application.yml: |
    micronaut:
      server:
        port: {{ .Values.deployment.containerPort }}
      application:
        name: bunnyMetrics

    {{ if .Values.deployment.velocityProperties }}
    velocityProperties: {{ .Values.deployment.velocityProperties }}
    {{- end }}
    trino:
      host: {{ required "Trino host is mandatory" .Values.deployment.trino.host }}
      port: {{ required "Trino port is mandatory" .Values.deployment.trino.port }}
      jdbc-properties:
      {{- range $index, $value := .Values.deployment.trino.jdbcProperties }}
        {{ $index }}: {{ $value }}
      {{- end }}