apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.name }}
  name: {{ template "bunny-metrics.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.deployment.image }}
          command: ["java"]
          args: ["-Dmicronaut.config.files=/conf/application.yml", "-jar" , "/home/app/application.jar"]
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          name: {{ .Values.name }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /conf
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.name }}