name: Merge README with Helm Chart specs

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'charts/**'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      ## Dependencies
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python package management
        run: |
          python -m pip install --upgrade pip
      - name: Install Frigate
        run: |
          pip install frigate
      - name: Make a temp copy of main README file
        uses: actions/checkout@v2
      ## Preparing files
      - name: Copy README.md
        run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Merging files
        run: |
          cp -f ${{ runner.temp }}/README.md .
          frigate gen charts/ >> README.md
      ## Pushing to GH pages
      - name: commit
        run: |
          git config user.name bunny_metrics_ci
          git config user.email "bunny_metrics_ci@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Merging README from main with Helm Chart specs"
          git push