name: Release Bunny-Metrics Chart

on:
  push:
    branches:
      - main

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      ## Dependencies
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python package management
        run: |
          python -m pip install --upgrade pip
      - name: Install Frigate
        run: |
          pip install frigate
      - name: Make a temp copy of main README file
        uses: actions/checkout@v2
      ## Preparing files
      - name: Generate and append Helm Chart specs into README.md
        run: |
          frigate gen charts/bunny-metrics/ >> README.md
      - name: Append Changelog into README.md
        run: |
          cat CHANGELOG.md >> README.md
      - name: Copy README.md to temp
        run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Copy README.md to gh-pages
        run: |
          cp -f ${{ runner.temp }}/README.md .
      ## Pushing to GH pages
      - name: commit
        run: |
          git config user.name bunny_metrics_ci
          git config user.email "bunny_metrics_ci@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Merging README from main with Helm Chart specs"
          git push
  release:
    needs: sync-readme
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup node
        uses: AutoModality/action-clean@1.1.0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
